In [7]:
import numpy as np

arr = []
for a in range(1, 21):
    arr.append(a)
array1 = np.array(arr)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [8]:
array2 = ([1,  2,  3],  [4,  5,  6],  [7,  8,  9], [10, 11, 12], [13, 14, 15])
array2

[[1, 2, 3, 4, 5, 6],
 [7, 8, 9, 10, 11, 12],
 [13, 14, 15, 16, 17, 18],
 [19, 20, 21, 22, 23, 24]]

In [10]:
array2[-1]

[19, 20, 21, 22, 23, 24]

In [11]:
array2

[[1, 2, 3, 4, 5, 6],
 [7, 8, 9, 10, 11, 12],
 [13, 14, 15, 16, 17, 18],
 [19, 20, 21, 22, 23, 24]]

In [12]:
array2

[[1, 2, 3, 4, 5, 6],
 [7, 8, 9, 10, 11, 12],
 [13, 14, 15, 16, 17, 18],
 [19, 20, 21, 22, 23, 24]]

In [13]:
array2

[[1, 2, 3, 4, 5, 6],
 [7, 8, 9, 10, 11, 12],
 [13, 14, 15, 16, 17, 18],
 [19, 20, 21, 22, 23, 24]]

In [14]:
array2

[[1, 2, 3, 4, 5, 6],
 [7, 8, 9, 10, 11, 12],
 [13, 14, 15, 16, 17, 18],
 [19, 20, 21, 22, 23, 24]]

In [15]:
clear



NameError: name 'clear' is not defined

In [17]:
array3 = np.array(range(10,200,10))
array3

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190])

In [18]:
slicee = array3[9:12].copy()
slicee

array([100, 110, 120])

In [19]:
slicee[:] = 0
array3

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190])

In [20]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # (3, 3) o'lchamli massiv
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr2d[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

arr2d

In [27]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr2d[:1,:2]

array([[1, 2]])

In [38]:
arr2d[1:2,:2]

array([[4, 5]])

In [39]:
# 3D array
arr3d = np.array([[[ 0,  1,  2],
                   [ 3,  4,  5],
                   [ 6,  7,  8]],

                  [[ 9, 10, 11],
                   [12, 13, 14],
                   [15, 16, 17]],

                  [[18, 19, 20],
                   [21, 22, 23],
                   [24, 25, 26]]])
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [76]:
array1 = arr3d[1][1:,:2]
array1

array([[12, 13],
       [15, 16]])

In [41]:
arr3d[2][:2,1:]

array([[19, 20],
       [22, 23]])

In [42]:
arr3d[1][:,1:2]

array([[10],
       [13],
       [16]])

In [43]:
arr3d[2][1:2,:]

array([[21, 22, 23]])

In [44]:
# Ismlar
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [45]:
# data
data = np.random.randn(7, 4)
data

array([[-1.43094987, -0.96824051,  0.18258092, -0.1473194 ],
       [-1.21802569,  0.7200958 , -1.91548968, -0.40271435],
       [ 0.39827624, -1.83174967,  1.99978723,  0.36035226],
       [-0.10638013,  1.67542817,  1.268048  ,  0.42772282],
       [ 0.06147411, -1.24296653, -1.17070499,  0.31894493],
       [-0.22563278,  0.11466897, -2.31420948,  1.67228611],
       [-0.8680851 , -1.60710738, -0.14393   ,  0.53726636]])

In [46]:
names == 'Hasan'

array([ True, False, False, False,  True, False, False])

In [47]:
data[names == 'Hasan']

array([[-1.43094987, -0.96824051,  0.18258092, -0.1473194 ],
       [ 0.06147411, -1.24296653, -1.17070499,  0.31894493]])

In [48]:
data[names == 'Elyor']

array([[-0.10638013,  1.67542817,  1.268048  ,  0.42772282],
       [-0.8680851 , -1.60710738, -0.14393   ,  0.53726636]])

In [51]:
data[names == 'Mirzabek',0:2 and 3]

array([[ 0.39827624, -1.83174967,  1.99978723]])

In [53]:
a = (names == 'Mirzabek') | (names == 'Javohir')
data[a,:2:]

array([[ 0.39827624, -1.83174967],
       [-0.22563278,  0.11466897]])

In [54]:
data

array([[-1.43094987, -0.96824051,  0.18258092, -0.1473194 ],
       [-1.21802569,  0.7200958 , -1.91548968, -0.40271435],
       [ 0.39827624, -1.83174967,  1.99978723,  0.36035226],
       [-0.10638013,  1.67542817,  1.268048  ,  0.42772282],
       [ 0.06147411, -1.24296653, -1.17070499,  0.31894493],
       [-0.22563278,  0.11466897, -2.31420948,  1.67228611],
       [-0.8680851 , -1.60710738, -0.14393   ,  0.53726636]])

In [57]:
if data[:]<0:
    data()==0
data

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [58]:
data[data<0] = 0
data

array([[0.        , 0.        , 0.18258092, 0.        ],
       [0.        , 0.7200958 , 0.        , 0.        ],
       [0.39827624, 0.        , 1.99978723, 0.36035226],
       [0.        , 1.67542817, 1.268048  , 0.42772282],
       [0.06147411, 0.        , 0.        , 0.31894493],
       [0.        , 0.11466897, 0.        , 1.67228611],
       [0.        , 0.        , 0.        , 0.53726636]])

In [59]:
def nd_array():
  """Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi), 
  qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv """
  arr = []
  for a in range(0,9,1):
    arr.append(a)
  array = np.array(arr)
  return array

In [61]:
nd_array()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
shape(nd_array)

NameError: name 'shape' is not defined

In [64]:
arr = []
for a in range(0,9,1):
    arr.append(a)
    array = np.array(arr)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
shape(array)

NameError: name 'shape' is not defined

In [67]:
array


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
array[6:8]

array([6, 7])

In [71]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
array[6:8]

array([6, 7])