In [2]:
import numpy as np
array = np.array(range(0,9))
array


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
arr = array.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
arr[2,:2]


array([6, 7])

In [13]:
arr[2,:2]

array([6, 7])

In [15]:
array1= [[[ 0,  1,  2],
                [ 3,  4,  5],
                [ 6,  7,  8]],

               [[ 9, 10, 11],
                [12, 13, 14],
                [15, 16, 17]],

               [[18, 19, 20],
                [21, 22, 23],
                [24, 25, 26]]]
array1

[[[0, 1, 2], [3, 4, 5], [6, 7, 8]],
 [[9, 10, 11], [12, 13, 14], [15, 16, 17]],
 [[18, 19, 20], [21, 22, 23], [24, 25, 26]]]

In [28]:
ar = np.array(array1, ndmin=2)
ar.ndim

3

In [32]:
a = np.array(range(0,27), ndmin=2)
a.reshape(2,3,3)

ValueError: cannot reshape array of size 27 into shape (2,3,3)